version: '3.7'

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb

    user:
        image: user-application:latest
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_started

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#            - /home/alexandr/SpringTestPrometheus/src/main/resources/localhost.crt:/etc/prometheus/localhost.crt
#            - /home/alexandr/SpringTestPrometheus/src/main/resources/localhost.key:/etc/prometheus/localhost.key

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin